feat: title page sequential view
Digraphy/frontend pull request #15
Opened 2024-12-18 13:43 UTC by S-Ou

not merging directly into main - but first into #14 

code not the tidiest - will refactor out but probs at a later stage

2024-12-19 08:40 UTC, pumbas600 requested changes
I noticed a few weird things 😓

2024-12-19 08:40 UTC, pumbas600 commented on src/app/title/page.tsx
> +	}
Typically I like to use arrow functions inside components.

```suggestion
	const cycleOrderType = () => {
		setOrderType(orderType === "sequential" ? "relational" : "sequential");
	}
```

2024-12-19 08:40 UTC, pumbas600 commented on src/app/title/page.tsx
> +})<{ alignRight?: boolean }>`
I'm pretty sure you can simplify this by prefixing the props with `$`
```suggestion
const SequentialAdjacent = styled(SequentialItem)<{ $alignRight?: boolean }>`
```

2024-12-19 08:40 UTC, pumbas600 commented on src/app/title/page.tsx
> +})<{ alignRight?: boolean }>`
As a sidenote, this alignment doesn't seem to do anything for me (Tested on Chrome)

2024-12-19 08:40 UTC, pumbas600 commented on src/app/title/page.tsx
> +					</>
When you shrink the page the lead poster becomes tiny...

![image](https://github.com/user-attachments/assets/e5bb3662-30d0-47e8-a1a4-44617f5f5a87)

I would probably use `flex: 1` , `flex: 2`, `flex: 1` for the three posters to ensure the lead poster always remains twice as wide as the side next/prev posters.

2024-12-19 09:15 UTC, sou323 commented on src/app/title/page.tsx
> +})<{ alignRight?: boolean }>`
💀 oh

it seems to still work visually so i'll just leave it as is for now

2024-12-19 09:20 UTC, S-Ou commented on src/app/title/page.tsx
> +					</>
yeah, was aware of this one... styling it was a nightmare and i think i'll just circle round to fixing this bug at a later date (plus at this size there's a chance we'll just be adding in some responsive styling anyways)

2024-12-21 07:31 UTC, pumbas600 approved these changes
Sweet, maybe create tickets for fixing those CSS bugs?

2024-12-21 08:31 UTC, merged